### ISSUE TITLE
Keybinding category: Addons vs. AddOns

### ISSUE THREAD

**Issue by fstenstrom** [NielsHeltner/wowhead-quick-link#3]
Hi, just tried your addon and it's really nice! I especially like the prefix/suffix part!

There's just one thing I had a problem with:
The category in the keybindings section is named "Add**O**n" instead of "Add**o**n", and since my other addons such as Bagnon and MoveAnything were under the latter, I couldn't find yours at first.

I don't know what the convention is, but I just wanted to give a heads up on this.

Note: I saw that some of my addons use "Other/Others" category as well.

**Comment by NielsHeltner** [comment]
Thanks for the kind words, and thanks for the heads up! This is definitely a curious issue.

I chose the "AddOns" since that is how Blizzard stylizes the word, and it is actually where most of my addons are (Angry Assignments, Bagnon, SavedInstances, SilverDragon, WeakAuras). I don't have any in the "Addon" category.

**Comment by fstenstrom** [comment]
Ah I see... Because it's the reverse with SilverDragon and WeakAuras for me. They just reference "ADDONS", and if I do something simple like `/run print(ADDONS)` with all addons disabled, this resolves to "Addons". I therefore guess that this is some global variable, and that it depends on localization (I currently use Spanish).

**Comment by NielsHeltner** [comment]
Aha, `/run print(ADDONS)` resolves to "AddOns" for me on English. Odd how the capitalization changes based on your localization. Nevertheless thank you! I would not have spotted this on my own.
